<!-- Logout Modal-->
<div class="modal fade bg-primary-transparency p-4" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg bg-white rounded" role="document">
        <div class="modal-content">
            <div class="modal-body mx-3">
                <div>
                    <h1 class="text-primary my-4 text-left" id="exampleModalLabel">Términos y condiciones</h1>
                </div>
<span class="text-sm text-justify">
<p>El presente contrato hace referencia a los t&eacute;rminos y condiciones generales del uso correcto de la plataforma comercial bajo el dominio web de www.armariomovil.com y los servicios ofrecidos por la compa&ntilde;&iacute;a Armario M&oacute;vil S.A.</p>
<p>Cualquier persona (en adelante &ldquo;Usuario&rdquo; o en plural &ldquo;Usuarios&rdquo;) que desee ingresar para usar la plataforma y/o los servicios podr&aacute; hacerlo sujet&aacute;ndose a los T&eacute;rminos y Condiciones Generales, junto con todas las dem&aacute;s pol&iacute;ticas y principios que rigen enwww.armariomovil.com y que son incorporados al presente contratos.</p>
<p><strong>Cualquier persona que no acepte esto t&eacute;rminos y condiciones generales, los cuales tienen car&aacute;cter obligatorio y vinculante, deber&aacute; abstenerse de utilizar la plataforma comercial y/o los servicios de la compa&ntilde;&iacute;a Armario M&oacute;vil S.A.</strong></p>
<p>El usuario debe leer, entender y aceptar todas las condiciones establecidas en los T&eacute;rminos y Condiciones Generales y en las Pol&iacute;ticas de Privacidad as&iacute; como en los dem&aacute;s documentos incorporados a los mismos por referencia, previo a su registraci&oacute;n como usuario de www.armariomovil.com.</p>
<p class="text-grey font-weight-bold"><strong>1 CONTRATO</strong></p>
<p>Los Servicios s&oacute;lo est&aacute;n disponibles para personas que tengan capacidad legal para generar un acuerdo legal. No podr&aacute;n utilizar los servicios las personas que no tengan la capacidad de generar un acuerdo legal, los menores de edad o usuarios de www.armariomovil.com que hayan sido suspendidos temporalmente o inhabilitados definitivamente.</p>
<p class="text-grey font-weight-bold"><strong>2 REGISTRO</strong></p>
<p>Es obligatorio completar el formulario de registro en todos sus campos con datos v&aacute;lidos para poder utilizar los servicios que brinda la plataforma de Armario M&oacute;vil. El futuro Usuario deber&aacute; completarlo con su informaci&oacute;n personal de manera exacta, precisa y real, por lo cual asume el compromiso de actualizar los Datos Personales y/o Comerciales conforme resulte necesario. Armario M&oacute;vil S.A. podr&aacute; utilizar diversos medios para identificar a sus Usuarios, pero Armario M&oacute;vil S.A. NO se responsabiliza por la certeza de los Datos Personales y/o Comerciales provistos por sus usuarios. Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
<p>Armario M&oacute;vil S.A. se reserva el derecho de solicitar alg&uacute;n comprobante y/o dato adicional a efectos de corroborar los Datos Personales o Comerciales, as&iacute; como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitaci&oacute;n, se dar&aacute; de baja todos los art&iacute;culos publicados, as&iacute; como las ventas realizadas sin enviar, sin que ello genere alg&uacute;n derecho a resarcimiento econ&oacute;mico por parte de Armario M&oacute;vil S.A.</p>
<p>El Usuario acceder&aacute; a su Cuenta Personal o Comercial (&ldquo;Mi Cuenta&rdquo;) mediante el ingreso de su e-mail y clave de seguridad personal elegida (&ldquo;Contrase&ntilde;a&rdquo;). El Usuario se obliga a mantener la confidencialidad de su Contrase&ntilde;a. La Cuenta es personal, &uacute;nica e intransferible.</p>
<p>El Usuario ser&aacute; responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma est&aacute; restringido al ingreso y uso de su Contrase&ntilde;a, de conocimiento exclusivo por el Usuario. El Usuario se compromete a notificar a Armario M&oacute;vil S.A. en forma inmediata y por medio id&oacute;neo y fehaciente, cualquier uso no autorizado de su Cuenta, as&iacute; como el ingreso por terceros no autorizados a la misma. Se aclara que est&aacute; prohibida la venta, cesi&oacute;n o transferencia de la Cuenta (incluyendo la calificaci&oacute;n y las ventas acumuladas) bajo ning&uacute;n t&iacute;tulo.</p>
<p>Armario M&oacute;vil S.A. se reserva el derecho de rechazar cualquier nueva solicitud de registro o de cancelar un registro previamente aceptado, sin que est&eacute; obligado a comunicar o exponer las razones de su decisi&oacute;n y sin que ello genere alg&uacute;n derecho a indemnizaci&oacute;n de da&ntilde;os o resarcimiento econ&oacute;mico.</p>
<p class="text-grey font-weight-bold"><strong>3 MODIFICACIONES DEL ACUERDO</strong></p>
<p>Armario M&oacute;vil S.A. podr&aacute; modificar los T&eacute;rminos y Condiciones Generales en cualquier momento haci&eacute;ndolo p&uacute;blico en www.armariomovil.com. Todos los t&eacute;rminos modificados entrar&aacute;n en vigencia a los 5 (cinco) d&iacute;as de su publicaci&oacute;n. Dentro de los 5 (cinco) d&iacute;as siguientes a la publicaci&oacute;n de las modificaciones introducidas, el Usuario deber&aacute; comunicar por e-mail la no aceptaci&oacute;n de las mismas; en ese caso quedar&aacute; disuelto el v&iacute;nculo contractual y ser&aacute; inhabilitado como Usuario siempre que no tenga deudas o art&iacute;culos pendientes por entregar. Vencido este plazo, se considerar&aacute; que el Usuario acepta los nuevos t&eacute;rminos y el contrato continuar&aacute; vinculando a ambas partes.</p>
<p class="text-grey font-weight-bold"><strong>4 PRODUCTOS A VENDER (BIENES)</strong></p>
<p><strong>4.1 DERECHO DE ADMISI&Oacute;N</strong>: Armario M&oacute;vil S.A. se guarda el derecho de aprobar o rechazar publicaciones de productos (bienes) por parte de los usuarios vendedores. Pudiendo, de esta forma, en cualquier momento dar de baja cualquier publicaci&oacute;n que no cumpla con los t&eacute;rminos y condiciones o con los est&aacute;ndares de calidad que considere pertinente.</p>
<p><strong>4.2 PUBLICACI&Oacute;N DE PRODUCTOS:</strong>&nbsp;El Usuario deber&aacute; ofrecer a la venta sus productos (bienes) en las categor&iacute;as y subcategor&iacute;as apropiadas para su anuncio. Las publicaciones podr&aacute;n incluir textos descriptivos, fotograf&iacute;as y videos pertinentes para la venta del bien, siempre que no violen ninguna disposici&oacute;n de este acuerdo o dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A.</p>
<p>El producto ofrecido en el perfil comercial por el Usuario Registrado debe ser exactamente descrito en cuanto a sus condiciones y caracter&iacute;sticas relevantes y reales a efectos de evitar publicidad enga&ntilde;osa. Se entiende y presume que mediante la inclusi&oacute;n del bien en www.armariomovil.com, el Usuario acepta que tiene la intenci&oacute;n y el derecho de vender el bien o est&aacute; facultado para ello por medio de su titular y lo tiene disponible para la entrega inmediata. Se establece que los precios de los productos publicados deber&aacute;n ser expresados con IMPUESTOS incluidos cuando corresponda la aplicaci&oacute;n del mismo, y en moneda del curso legal en Ecuador (D&oacute;lares Americanos).</p>
<p>Armario M&oacute;vil S.A. podr&aacute; remover cualquier publicaci&oacute;n cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto.</p>
<p>Se deja expresamente establecido que ninguna descripci&oacute;n, fotograf&iacute;a o video podr&aacute; contener datos personales o de contacto, tales como, y sin limitarse a, n&uacute;meros telef&oacute;nicos, direcci&oacute;n de e-mail, direcci&oacute;n postal, direcciones de p&aacute;ginas de internet que contengan datos como los mencionados anteriormente. No podr&aacute; publicitarse otros medios de pagos, distintos de los enunciados por la plataforma comercial <a href="http://www.armariomovil.com">www.armariomovil.com</a>.</p>
<p>En caso que se infrinja cualquiera de las disposiciones establecidas en esta cl&aacute;usula, Armario M&oacute;vil S.A. podr&aacute; editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicaci&oacute;n donde se encuentre la infracci&oacute;n y en ning&uacute;n caso se devolver&aacute;n o bonificar&aacute;n los cargos de publicaci&oacute;n.</p>
<p><strong>4.3 INCLUSI&Oacute;N DE FOTOGRAF&Iacute;AS Y VIDEOS</strong>: El usuario puede incluir fotograf&iacute;as y videos del producto ofrecido siempre que las mismas se correspondan con el art&iacute;culo. El usuario declara y garantiza que est&aacute; facultado para incluir las im&aacute;genes, fotograf&iacute;as u otros formatos multimedia contenidas en sus publicaciones, siendo responsable por cualquier infracci&oacute;n a derechos de terceros.</p>
<p>Armario M&oacute;vil S.A. podr&aacute; impedir la publicaci&oacute;n de la fotograf&iacute;a o video, e incluso del producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes T&eacute;rminos y Condiciones.</p>
<p>El usuario otorga a Armario M&oacute;vil S.A. una autorizaci&oacute;n gratuita y sin l&iacute;mite de tiempo para publicar y/o adaptar las im&aacute;genes incluidas en sus publicaciones con fines comunicacionales en todos los sitios web propios, externos, redes sociales y/o por cualquier medio que Armario M&oacute;vil S.A. lo considere necesario.</p>
<p><strong>4.4 ART&Iacute;CULOS PROHIBIDOS:</strong>&nbsp;S&oacute;lo podr&aacute;n ser ingresados en las listas de bienes ofrecidos, aquellos cuya venta no se encuentre t&aacute;cita o expresamente prohibida en los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A. o por la ley vigente.</p>
<p><strong>4.5 PROTECCI&Oacute;N DE PROPIEDAD INTELECTUAL:</strong>&nbsp;En caso que Armario M&oacute;vil S.A. sospeche que se est&aacute; cometiendo o se ha cometido una actividad il&iacute;cita o infractora de derechos de propiedad intelectual o industrial, Armario M&oacute;vil S.A. se reserva el derecho de adoptar todas las medidas que entienda adecuadas.</p>
<p class="text-grey font-weight-bold"><strong>5 PRIVACIDAD DE LA INFORMACI&Oacute;N</strong></p>
<p>Para utilizar los Servicios ofrecidos por Armario M&oacute;vil S.A, los Usuarios deber&aacute;n facilitar determinados datos de car&aacute;cter personal y/o comercial. Su informaci&oacute;n personal y comercial se procesa y almacena en servidores o medios magn&eacute;ticos que mantienen altos est&aacute;ndares de seguridad y protecci&oacute;n tanto f&iacute;sica como tecnol&oacute;gica.</p>
<p>Los tipos de informaci&oacute;n personal y confidencial que recopilamos incluyen, entre otras cosas: nombre y datos de contacto, informaci&oacute;n de identificaci&oacute;n (por ejemplo, fecha de nacimiento), informaci&oacute;n demogr&aacute;fica y de perfil (g&eacute;nero, edad, etc.), informaci&oacute;n relacionada con la actividad que se publicita.</p>
<p>El USUARIO entiende y autoriza a Armario M&oacute;vil S.A. para que a modo de resumen, recopile informaci&oacute;n personal y confidencial en diversas circunstancias, tales como pero no limitadas a: (i) el registro, (ii) interacciones con los Gestores, aplicaci&oacute;n armariomovil.com y otras aplicaciones relacionadas, (iii) realizaci&oacute;n de consultas, (iv) solicitud y/o uso de nuestros productos/servicios.&nbsp;</p>
<p>Los Gestores (y para evitar dudas, las Compa&ntilde;&iacute;as, terceros relacionados, corporativos y afiliados) tambi&eacute;n pueden usar, tratar y divulgar la informaci&oacute;n personal para proporcionar comunicaciones de marketing que puedan ser de inter&eacute;s del USUARIO, incluyendo sin limitaci&oacute;n, sobre nuevos productos y servicios como productos y servicios asociados o cualquier cambio/mejora. Las comunicaciones pueden proporcionarse de forma continua por cualquier medio de comunicaci&oacute;n.</p>
<p>A trav&eacute;s de la aceptaci&oacute;n de este documento, autorizo adem&aacute;s a que se utilicen mis datos personales para fines de marketing. Si no desea recibir comunicaciones de marketing directo, deber&aacute; indicarlo a los medios de contacto definidos por los Gestores y terceros relacionados.</p>
<p>El USUARIO autoriza expresa e indefinidamente a Armario M&oacute;vil S.A., para que obtenga de cualquier fuente de informaci&oacute;n, incluidos los Bur&oacute;s de Informaci&oacute;n Crediticia, o como pasen a llamarse en el futuro, autorizados para operar en el pa&iacute;s, las referencias personales y/o patrimoniales anteriores o posteriores a la suscripci&oacute;n de esta autorizaci&oacute;n, sea como deudor principal, codeudor o garante, sobre el comportamiento crediticio, manejo de cuenta(s), corriente(s), de ahorro, tarjetas de cr&eacute;dito, etc., y en general al cumplimiento de las obligaciones y dem&aacute;s activos, pasivos, datos personales y/o patrimoniales, aplicables para uno o m&aacute;s de los servicios y productos que brindan las Instituciones del Sistema Financiero y Comercial, seg&uacute;n corresponda, as&iacute; como para que obtenga informaci&oacute;n que sirva directa o indirectamente para la evaluaci&oacute;n y procesamiento del perfil comercial presente o futuro cualquiera sea su tipo, verificaci&oacute;n de datos, validaci&oacute;n de identidad y prevenci&oacute;n de fraude, identificaci&oacute;n de potenciales usos indebidos y fraudulentos del aplicativo a uso.</p>
<p>&nbsp;</p>
<p>El USUARIO faculta expresamente a Armario M&oacute;vil S.A. a transferir o entregar informaci&oacute;n, referente a operaciones crediticias, sea como deudor principal, codeudor o garante, a autoridades competentes y organismos de control, cuando as&iacute; lo requieran as&iacute; como a otras instituciones o personas jur&iacute;dicas legalmente facultadas.</p>
<p>El USUARIO otorga su consentimiento a&nbsp;Armario M&oacute;vil S.A. para que pueda realizar tratamientos de los datos personales as&iacute; mismo autoriza a que los referidos tratamientos puedan ser realizados directamente por&nbsp;Armario M&oacute;vil S.A., o por un tercero a quien &eacute;sta pudiera encargar dichos tratamientos. El tratamiento y mantenimiento de los datos podr&aacute; hac&eacute;rselo en el pa&iacute;s o en exterior.</p>
<p class="text-grey font-weight-bold"><strong>6 OBLIGACIONES DE LOS USUARIOS</strong></p>
<p><strong>6.1 OBLIGACIONES DEL COMPRADOR:</strong>&nbsp;Durante los horarios en el que el Usuario Vendedor publique en su perfil comercial, los Usuarios interesados podr&aacute;n adquirir los productos (bienes) publicados. La compra se cierra una vez que el usuario reciba el producto por medio del el proveedor log&iacute;stico asignado en www.armariomovil.com y posterior calificaci&oacute;n de la compra del art&iacute;culo.</p>
<p>El Comprador est&aacute; obligado a completar la operaci&oacute;n si ha realizado una compra por un art&iacute;culo, salvo que la operaci&oacute;n est&eacute; prohibida por la ley o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A., en cuyo caso no estar&aacute; obligado a concretar la operaci&oacute;n.</p>
<p>El Comprador est&aacute; obligado a abonarle a la compa&ntilde;&iacute;a Armario M Armario Minado logt producto adquirido en perfil comercial&oacute;vil el costo generado por el servicio log&iacute;stico para la entrega del bien a su domicilio o en su sucursal m&aacute;s cercana, en el momento que esto se produzca, las tarifas fijadas por dicha empresa.</p>
<p>Al comprar un art&iacute;culo el Usuario acepta quedar obligado por las condiciones de venta incluidas en la descripci&oacute;n del art&iacute;culo en la medida en que las mismas no infrinjan las leyes o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A. La compra es irrevocable salvo en circunstancias excepcionales.</p>
<p>Tal como lo establece la normativa fiscal vigente, el comprador debe exigir una factura con IVA por parte de Armario M&oacute;vil como comprobante de la operaci&oacute;n.</p>
<p><strong>6.2. OBLIGACIONES DEL VENDEDOR:</strong>&nbsp;El Usuario Vendedor debe tener capacidad legal para vender el producto (bien) objeto de su oferta.</p>
<p>El Usuario Vendedor estar&aacute; obligado a emitir a Armario M&oacute;vil S.A. una factura incluido el IVA por la venta de su producto (bien) dentro de la plataforma de www.armariomovil.com</p>
<p>Si el Usuario Vendedor ha recibido una alerta de compra sobre el producto (bien) publicado, queda obligado a generar la orden de env&iacute;o bajo los siguientes motivos:</p>
<p><strong>Env&iacute;o Local:</strong> Despachar el producto dentro de los primeros 30 minutos de generarse la alerta de la venta de su producto y entregar el bien al Courier designado por Armario M&oacute;vil S.A. para ser recibido por el comprador dentro de las primeras 3 horas de adquisici&oacute;n.</p>
<p><strong>Env&iacute;o Nacional:</strong> Despachar el producto dentro de las dos primeras horas que se genera la alerta de la venta de su producto y debe entregar el bien al Courier designado por Armario M&oacute;vil S.A. para ser recibido por el comprador dentro de los siguientes rangos:</p>
<p><strong>Capitales de provincia:</strong> De uno a dos d&iacute;as laborables desde la adquisici&oacute;n del producto.</p>
<p><strong>Ciudades secundarias:</strong> De tres a cuatro d&iacute;as laborables desde la adquisici&oacute;n del producto.</p>
<p><strong>Ciudades alejadas:</strong> Un m&aacute;ximo de hasta cinco d&iacute;as laborables y todo depender&aacute; de la lejan&iacute;a.</p>
<p><strong>Env&iacute;o Gal&aacute;pagos:</strong> Despachar el producto dentro de las dos primeras horas que se genera la alerta de la venta de su producto y debe entregar el bien al Courier designado por Armario M&oacute;vil S.A. para ser recibido por el comprador hasta en 10 d&iacute;as laborables desde la adquisici&oacute;n.</p>
<p>De no cumplirse con los pasos de env&iacute;o, Armario M&oacute;vil S.A. sancionar&aacute; al vendedor y se entregar&aacute; al Comprador un cup&oacute;n con el monto equivalente a la compra realizada en www.aArmariomoM&oacute;vil.com, para ser utilizado en otra compra dentro de la plataforma.</p>
<p>Armario M&oacute;vil S.A. requiere que los Usuarios vendedores anuncien las opciones de pago para la venta de sus productos (bienes) dentro de la plataforma mediante la utilizaci&oacute;n de los Servicios de Gesti&oacute;n de Pagos Online ofrecidas por Armario M&oacute;vil S.A. para el cobro del bien ofertado y de las tarifas por la utilizaci&oacute;n de los servicios.</p>
<p>Dado que Armario M&oacute;vil S.A. es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el Vendedor ser&aacute; responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus art&iacute;culos, sin que pudiera imput&aacute;rsele a Armario M&oacute;vil S.A. alg&uacute;n tipo de responsabilidad por incumplimientos en tal sentido.</p>
<p>Como se menciona anteriormente, Armario M&oacute;vil S.A. pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite comunicarse mediante internet para encontrar una forma de vender o comprar productos (bienes). Armario M&oacute;vil S.A. es participante del proceso de negociaci&oacute;n entre las partes. Por eso, Armario M&oacute;vil S.A. si es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p>
<p><strong>6.3 ENV&Iacute;OS</strong></p>
<p>Los env&iacute;os deben realizarse exclusivamente por los medios que Armario M&oacute;vil S.A. pone a disposici&oacute;n de usuarios vendedores y compradores en su plataforma. De realizarse env&iacute;os por fuera de la plataforma, Armario M&oacute;vil no tendr&aacute; control de la operaci&oacute;n, como tampoco tendr&aacute; responsabilidad del pago del bien vendido al usuario vendedor.</p>
<p>Las empresas autorizadas para los env&iacute;os generados desde Armario M&oacute;vil son:</p>
<p><strong>Env&iacute;o Local:</strong> Sera ejecutado en las ciudad de Quito y Guayaquil por medio de la empresa GACELA DELIVERY.</p>
<p><strong>Env&iacute;o Nacional:</strong> Sera ejecutado a nivel nacional por medio de la empresa URBANO EXPRESS.</p>
<p><strong>Env&iacute;o Gal&aacute;pagos:</strong> Sera ejecutado a nivel nacional por medio de la empresa URBANO EXPRESS.</p>
<p><strong>6.4 REENV&Iacute;OS</strong></p>
<p>Si el usuario comprador no se encontrara presente en su domicilio cuando se le realiza la visita del Courier para dejarle el pedido, la empresa de Courier devolver&aacute; el producto a la direcci&oacute;n del remitente (Usuario Vendedor) y el comprador deber&aacute; pagar nuevamente el valor del env&iacute;o m&aacute;s las respectivas penalidades.</p>
<p>Desde la fecha de devoluci&oacute;n del Courier, el usuario comprador tiene 5 d&iacute;as corridos para contactarse v&iacute;a email o telef&oacute;nica con el departamento de atenci&oacute;n al cliente y solicitar el reenv&iacute;o de su pedido. El usuario comprador puede elegir recibir el pedido con cargo en el mismo destino de su compra anterior o retirar sin cargo en los puntos de entrega de Armario M&oacute;vil S.A.</p>
<p>Antes de recibir o retirar el paquete en los puntos de entrega, el comprador deber&aacute; abonar una multa, en concepto de los env&iacute;os previamente realizados y no cumplidos por su parte. El monto de la multa lo fijar&aacute; Armario M&oacute;vil S.A. al momento en que el reenv&iacute;o es solicitado y puede sufrir modificaciones de acuerdo a la ciudad o provincia.</p>
<p>En caso de no querer abonar el costo de la multa, el pedido no ser&aacute; devuelto, ni reenviado, como as&iacute; tampoco se reintegrar&aacute; el dinero de esa compra, ya que Armario M&oacute;vil S.A. ha asumido todos los costos en concepto de env&iacute;os y reenv&iacute;os de ese pedido.</p>
<p>Pasados los 6 d&iacute;as corridos, el producto ya no podr&aacute; ser retirado ni solicitar su reenv&iacute;o.&nbsp;Armario M&oacute;vil S.A. estar&aacute; en condiciones de desbloquear el stock y podr&aacute; revender el producto.</p>
<p>Los reenv&iacute;os se realizan s&oacute;lo una vez por usuario comprador por n&uacute;mero de pedido. En caso que por segunda vez el usuario comprador no retire el pedido y el mismo sea devuelto a la direcci&oacute;n del remitente o a nuestras oficinas,&nbsp;el producto ya no podr&aacute; ser retirado ni solicitar su reenv&iacute;o.&nbsp;Armario M&oacute;vil S.A. estar&aacute; en condiciones de desbloquear el stock y podr&aacute; revender el producto.</p>
<p><strong>6.5 CAMBIOS O DEVOLUCIONES</strong></p>
<p>El usuario comprador puede solicitar el cambio de su producto dentro de las primeras 72 horas corridas desde que fue recibido el bien bajo una justificaci&oacute;n razonable donde se identifique a la prenda como no adecuada. Los motivos para solicitar una devoluci&oacute;n son cuando no cumple con el color, talla o calidad descrita.</p>
<p><strong>El proceso para solicitar la devoluci&oacute;n es:</strong></p>
<p>1) Una vez que el pedido se da como Completado, presiona el bot&oacute;n DEVOLVER en el pedido que se encontrar&aacute; en la secci&oacute;n Mis Compras. Este bot&oacute;n s&oacute;lo va a estar disponible por las primeras 72 horas desde que se recibi&oacute; el producto.</p>
<p>2) Elige el producto que deseas devolver, llena el formulario de devoluci&oacute;n con el motivo del cambio.</p>
<p>3) Armario M&oacute;vil validar&aacute; la solicitud recibida y solicitar&aacute; los respaldos necesarios que comprobar la inconformidad.</p>
<p>4) El usuario comprador recibir&aacute; una notificaci&oacute;n donde se le indicar&aacute; si fue aprobado la solicitud o si fue negada la solicitud.</p>
<p>5) En caso de que el usuario comprador reciba la aprobaci&oacute;n de su solicitud de devoluci&oacute;n, deber&eacute; empacar nuevamente el o los productos que deseas devolver.</p>
<p>6) En el caso de env&iacute;o Nacional o Gal&aacute;pagos, el usuario comprador deber&aacute; imprimir una gu&iacute;a de env&iacute;o provista por Armario M&oacute;vil S.A. y la misma debe ser colocada en el paquete sellado con el producto que ser&aacute; entregado al Courier &ldquo;URBANO EXPRESS&rdquo;.</p>
<p>7) En el caso de env&iacute;o Local, el usuario comprador deber&aacute; entregar el paquete sellado con el producto al proveedor de Courier &ldquo;GACELA DELIVERY&rdquo;.</p>
<p>IMPORTANTE: El bot&oacute;n de DEVOLVER va a estar disponible durante 72 horas y te dar&aacute;s cuenta que el tiempo comienza a correr cuando recibas un email por parte de Armario M&oacute;vil para calificar a la tienda.</p>
<p>El costo que implique el reenv&iacute;o del producto corre por cuenta exclusiva del usuario vendedor.</p>
<p>8) Si por alg&uacute;n motivo el usuario vendedor no puede entregar el nuevo producto, Armario M&oacute;vil S.A. devolver&aacute; al usuario comprador el monto total de la transacci&oacute;n por medio de un cup&oacute;n que podr&aacute; ser utilizado en otra compra.</p>
<p>Dicho cup&oacute;n podr&aacute; ser utilizado dentro de los primeros 60 d&iacute;as de generarse el c&oacute;digo de descuento, por una sola vez y para adquirir un producto de igual o menor valor. Si la nueva compra es de un valor mayor, el usuario comprador deber&aacute; pagar la diferencia. Los c&oacute;digos de cupones no son acumulables con otras promociones. No podr&aacute; realizarse un nuevo cambio de un pedido adquirido con un cup&oacute;n de cambio.</p>
<p>Pasadas las 72 horas corridas de recibido o retirado el producto, no podr&aacute; solicitarse el cambio del mismo bajo ning&uacute;n concepto.</p>
<p><strong>6.5.1 DEVOLUCIONES DE PRODUCTOS ENTREGADOS</strong></p>
<p>Todas las solicitudes de devoluciones hechas por los usuarios compradores son enviadas a la empresa Armario M&oacute;vil S.A., donde el &aacute;rea de calidad realizar&aacute; la validaci&oacute;n correspondiente.</p>
<p>En caso de que las prendas hayan sido enviadas por el vendedor con caracter&iacute;sticas distintas a lo acordado o en mal estado, Armario M&oacute;vil S.A. no pagar&aacute; al vendedor por su producto y el usuario podr&aacute; ser penalizado econ&oacute;micamente o con la suspensi&oacute;n de su perfil comercial. Adicionalmente el producto podr&aacute; ser retenido en las oficinas de Armario M&oacute;vil o devuelto al vendedor a la direcci&oacute;n de despacho, asumiendo el vendedor todos los gastos derivados de este nuevo env&iacute;o.</p>
<p>Pasado dicho per&iacute;odo, las prendas no podr&aacute;n ser reclamadas bajo ning&uacute;n concepto.</p>
<p>Las penalidades econ&oacute;micas ser&aacute;n cobradas del pr&oacute;ximo saldo a favor a recibir por sus otras ventas generadas en www.armariomovil.com</p>
<p class="text-grey font-weight-bold"><strong>7 PROHIBICIONES</strong></p>
<p>Los Usuarios no podr&aacute;n:</p>
<p>(a) Mantener ning&uacute;n tipo de comunicaci&oacute;n externa por e-mail, o por cualquier otro medio (incluyendo las redes sociales) durante la oferta del bien con ninguno de los Usuarios que participan en la misma;</p>
<p>(b) Dar a conocer sus datos personales o de otros usuarios (incluyendo pero sin limitar Facebook, Instagram, Twitter y/ o cualquier otra red social);</p>
<p>(c) Aceptar datos personales proporcionados por otros usuarios (incluyendo pero sin limitar Facebook, Instagram, Twittery/o cualquier otra red social);</p>
<p>(d) Publicar o vender art&iacute;culos prohibidos por los T&eacute;rminos y Condiciones Generales, dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A. o leyes vigentes;</p>
<p>(e) Insultar o agredir a otros Usuarios.</p>
<p>Este tipo de actividades ser&aacute;n investigadas por Armario M&oacute;vil S.A. y el infractor podr&aacute; ser sancionado con la suspensi&oacute;n o cancelaci&oacute;n de la venta o compra e incluso de su inscripci&oacute;n como Usuario de Armario M&oacute;vil y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuraci&oacute;n de delitos o contravenciones o los perjuicios civiles que pueda causar a los Usuarios oferentes.</p>
<p class="text-grey font-weight-bold"><strong>8 VIOLACIONES DEL SISTEMA O BASES DE DATOS</strong></p>
<p>No est&aacute; permitida ninguna acci&oacute;n o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de Armario M&oacute;vil S.A. como en las ofertas, descripciones, cuentas o bases de datos de Armario M&oacute;vil. Cualquier intromisi&oacute;n, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato har&aacute;n posible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, as&iacute; como lo har&aacute; responsable de indemnizar los da&ntilde;os ocasionados.</p>
<p class="text-grey font-weight-bold"><strong>9 SANCIONES Y/O SUSPENSI&Oacute;N DE OPERACIONES</strong></p>
<p>Sin perjuicio de otras medidas, Armario M&oacute;vil S.A. podr&aacute; advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicaci&oacute;n, aplicar una sanci&oacute;n que impacte negativamente en la reputaci&oacute;n de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestaci&oacute;n de sus Servicios si</p>
<p>(a) Si se quebrantara alguna ley, o cualquiera de las estipulaciones de los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de Armario M&oacute;vil S.A.;</p>
<p>(b) Si incumpliera sus compromisos como Usuario Comprador y/o Vendedor;</p>
<p>(c) Si se incurriera a criterio de Armario M&oacute;vil en conductas o actos dolosos o fraudulentos;</p>
<p>(d) No pudiera verificarse la identidad del Usuario o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea;</p>
<p>(e) Armario M&oacute;vil S.A. entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las public&oacute;, para Armario M&oacute;vil o para los Usuarios. En el caso de la suspensi&oacute;n o inhabilitaci&oacute;n de un Usuario, todos los art&iacute;culos que tuviera publicados ser&aacute;n removidos del sistema y en ning&uacute;n caso se devolver&aacute;n o bonificar&aacute;n los cargos involucrados.</p>
<p class="text-grey font-weight-bold"><strong>10 RESPONSABILIDAD</strong></p>
<p>Armario M&oacute;vil S.A. s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite conectarse comercialmente mediante internet para encontrar una forma de vender o comprar productos (bienes). Armario M&oacute;vil no es el propietario de los productos ofrecidos (bienes), no tiene posesi&oacute;n de ellos ni los ofrece en venta. Armario M&oacute;vil no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no ser&aacute; responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los productos ofrecidos (bienes), adquiridos o enajenados por los Usuarios, as&iacute; como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los art&iacute;culos que publica para su venta y por las compras que realiza.</p>
<p>El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ning&uacute;n caso Armario M&oacute;vil S.A. ser&aacute; responsable por lucro cesante, o por cualquier otro da&ntilde;o y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por art&iacute;culos publicados a trav&eacute;s de Armario M&oacute;vil.</p>
<p>En caso que uno o m&aacute;s Usuarios o alg&uacute;n tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a Armario M&oacute;vil S.A. y a sus accionistas, directores, gerentes, empleados, agentes, operarios, representantes y apoderados.</p>
<p class="text-grey font-weight-bold"><strong>11 ALCANCE DE LOS SERVICIOS DE </strong><strong>ARMARIO M&Oacute;VIL</strong></p>
<p>Este acuerdo no crea ning&uacute;n contrato de sociedad, de mandato, de franquicia, o relaci&oacute;n laboral entre Armario M&oacute;vil S.A. y el Usuario. El Usuario reconoce y acepta que Armario M&oacute;vil no es parte en ninguna operaci&oacute;n, ni tiene control alguno sobre la calidad, seguridad o legalidad de los art&iacute;culos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar art&iacute;culos.</p>
<p class="text-grey font-weight-bold"><strong>12 FALLAS EN EL SISTEMA</strong></p>
<p>Armario M&oacute;vil S.A. no se responsabiliza por cualquier da&ntilde;o, perjuicio o p&eacute;rdida al Usuario causados por fallas en el sistema, en el servidor o en internet. Armario M&oacute;vil tampoco ser&aacute; responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a ra&iacute;z de cualquier transferencia de datos, archivos, im&aacute;genes, textos, o audio contenidos en el mismo. Los Usuarios NO podr&aacute;n imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades t&eacute;cnicas o fallas en los sistemas o en Internet. Armario M&oacute;vil S.A. no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otra circunstancia ajena a Armario M&oacute;vil; en tales casos se procurar&aacute; restablecerlo con la mayor celeridad posible sin que por ello pueda imput&aacute;rsele alg&uacute;n tipo de responsabilidad. Armario M&oacute;vil S.A. no ser&aacute; responsable por ning&uacute;n error u omisi&oacute;n contenidos en su sitio web.</p>
<p class="text-grey font-weight-bold"><strong>13 TARIFAS Y FACTURACI&Oacute;N</strong></p>
<p>El registro, suscripci&oacute;n y publicaci&oacute;n de productos en www.armariomovil.comes gratuita, solamente pagar&aacute; una comisi&oacute;n base del 30% por la venta del producto dentro de la plataforma comercial de Armario M&oacute;vil S.A., esto se cumplir&aacute; solamente cuando la operaci&oacute;n se concrete favorablemente para las dos partes.</p>
<p>Adicionalmente el Usuario Vendedor por su propia voluntad podr&aacute; mejorar su nivel de suscripci&oacute;n pagando mensualmente $8,99 d&oacute;lares americanos en el plan Closet y $14,99 d&oacute;lares americanos en el plan Armario.</p>
<p>Adem&aacute;s, los Usuarios que deseen por su voluntad propia destacar su publicaci&oacute;n, deber&aacute;n pagar por unidad de anuncio el valor de $4,99 d&oacute;lares americanos en la categor&iacute;a CHIC y $7,99 d&oacute;lares americanos en la categor&iacute;a FASHION; antes de completar el proceso de destacar el anuncio, se deber&aacute; pagar dichos montos, directamente en la plataforma de <a href="http://www.armariomovil.com">www.armariomovil.com</a></p>
<p>Armario M&oacute;vil S.A. se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual ser&aacute; notificado a los Usuarios, en la forma establecida en la Cl&aacute;usula tercera. Sin embargo, Armario M&oacute;vil podr&aacute; modificar temporalmente la Pol&iacute;tica de Tarifas y las tarifas por sus servicios por raz&oacute;n de promociones, siendo efectivas estas modificaciones cuando se haga p&uacute;blica la promoci&oacute;n o se realice el anuncio.</p>
<p>Armario M&oacute;vil S.A. se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido.</p>
<p>En caso de haberse facturado cargos que no hubiesen correspondido, el Usuario deber&aacute; comunicarse con nuestro equipo de Atenci&oacute;n al Cliente para resolver dicha cuesti&oacute;n.</p>
<p class="text-grey font-weight-bold"><strong>14 PAGOS Y COBRO DE COMISIONES</strong></p>
<p>Armario M&oacute;vil S.A. liquidar&aacute; a cada usuario vendedor, de manera mensual, los montos de los productos vendidos y enviados a trav&eacute;s de la soluci&oacute;n log&iacute;stica brindada por Armario M&oacute;vil en concepto de cierre mensual de ventas.</p>
<p>Las ventas realizadas hasta el d&iacute;a 21 de cada mes ser&aacute;n pagadas el d&iacute;a 25 de cada mes, en caso de coincidir con fin de semana o feriado el pago se realizar&aacute; primer d&iacute;a h&aacute;bil , cabe recalcar que en el pago ya vendr&aacute; descontado las comisiones seg&uacute;n el perfil de suscripci&oacute;n y adicionalmente no existir&aacute; ning&uacute;n recargo econ&oacute;mico, el Usuario vendedor deber&aacute; registrar los datos de su cuenta bancaria en la secci&oacute;n &ldquo;M&eacute;todos de Cobro&rdquo; dentro de Saldos y Cobros.</p>
<p>El Usuario vendedor podr&aacute; solicitar en cualquier momento el pago anticipado de sus ventas pero tendr&aacute; un costo administrativo de $3 d&oacute;lares americanos y el pago se realizar&aacute; hasta en 48 horas despu&eacute;s de generar su solicitud.</p>
<p class="text-grey font-weight-bold"><strong>15 SERVICIOS LOG&Iacute;STICOS</strong></p>
<p>Armario M&oacute;vil S.A. dispondr&aacute; seg&uacute;n la ciudad de despacho y entrega variaos modalidades de env&iacute;o con dos proveedores log&iacute;sticos.</p>
<p><strong>15.1 Env&iacute;o Local:</strong> El servicio ser&aacute; prestado por la empresa GACELA DELIVERY, tendr&aacute; un costo de $3.50 que ser&aacute;n pagados en d&oacute;lares americanos, se genera esta modalidad de env&iacute;o cuando el vendedor y el comprador se encuentran en la misma ciudad, por ejemplo cuando un usuario comprador de la ciudad de Quito adquiere el producto de un vendedor que despacha desde la ciudad de Quito.</p>
<p>Las ciudades que entran en la modalidad de env&iacute;o local son Quito y Guayaquil.</p>
<p><strong>15.2 Env&iacute;o Nacional:</strong> El servicio ser&aacute; prestado por la empresa URBANO EXPRESS, tendr&aacute; un costo de $5.50 que ser&aacute;n pagados en d&oacute;lares americanos, se genera esta modalidad de env&iacute;o cuando el vendedor y el comprador no se encuentran dentro de la red de cobertura de el ENV&Iacute;O LOCAL, por ejemplo cuando un usuario comprador de la ciudad de Quito adquiere el producto de un vendedor que despacha desde la ciudad de Ambato.</p>
<p>Las ciudades que entran en la modalidad de env&iacute;o nacional son todas las ciudades del Ecuador que cuenten con la cobertura de URBANO EXPRESS.</p>
<p><strong>15.3 Env&iacute;o Gal&aacute;pagos:</strong> El servicio ser&aacute; prestado por la empresa URBANO EXPRESS, tendr&aacute; un costo de $13 que ser&aacute;n pagados en d&oacute;lares americanos, se genera esta modalidad de env&iacute;o cuando el comprador reside en las Islas Gal&aacute;pagos y el vendedor reside en Ecuador Continental, por ejemplo cuando un usuario comprador de las Islas Gal&aacute;pagos adquiere el producto de un vendedor que despacha desde la ciudad de Cuenca.</p>
<p class="text-grey font-weight-bold"><strong>16 SISTEMA DE REPUTACI&Oacute;N</strong></p>
<p>Debido a que la verificaci&oacute;n de la identidad de los Usuarios en Internet es dif&iacute;cil, Armario M&oacute;vil S.A. no puede confirmar ni confirma la identidad pretendida de cada Usuario. Por ello el Usuario cuenta con un sistema de reputaci&oacute;n de Usuarios que es actualizado peri&oacute;dicamente en base a datos vinculados con su actividad en el sitio y a los comentarios ingresados por los Usuarios seg&uacute;n las operaciones que hayan realizado. Tanto aquellos Usuarios que hayan resultado ganadores de una oferta como el vendedor deber&aacute;n ingresar una calificaci&oacute;n informando acerca de la concreci&oacute;n o no de la operaci&oacute;n; tambi&eacute;n podr&aacute;n ingresar un comentario si as&iacute; lo desean. Este sistema de reputaci&oacute;n, adem&aacute;s constar&aacute; de un espacio donde los Usuarios podr&aacute;n hacer comentarios y r&eacute;plicas a las calificaciones recibidas y acceder a los mismos. Dichos comentarios ser&aacute;n incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan.</p>
<p>En virtud que las calificaciones, comentarios y r&eacute;plicas son realizados por los Usuarios, &eacute;stos ser&aacute;n incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan. Armario M&oacute;vil S.A. no tiene obligaci&oacute;n de verificar la veracidad o exactitud de los mismos y NO se responsabiliza por los dichos all&iacute; vertidos por cualquier Usuario, por las ofertas de compras o ventas que los Usuarios realicen teni&eacute;ndolos en cuenta o por la confianza depositada en las calificaciones de la contraparte o por cualquier otro comentario expresado dentro del sitio o a trav&eacute;s de cualquier otro medio, incluido el correo electr&oacute;nico. Armario M&oacute;vil se reserva el derecho de editar y/o eliminar aquellos comentarios que sean considerados inadecuados u ofensivos. Armario M&oacute;vil mantiene el derecho de excluir a aquellos Usuarios que sean objeto de comentarios negativos provenientes de fuentes distintas. Para obtener mayor informaci&oacute;n sobre el sistema de calificaciones.</p>
<p class="text-grey font-weight-bold"><strong>17 PROPIEDAD INTELECTUAL</strong></p>
<p>Los contenidos de las pantallas relativas a los servicios de <a href="http://www.armariomovil.com">www.armariomovil.com</a> como as&iacute; tambi&eacute;n los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de Armario M&oacute;vil S.A. y est&aacute;n protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y dise&ntilde;os industriales. El uso indebido y la reproducci&oacute;n total o parcial de dichos contenidos quedan prohibidos, salvo autorizaci&oacute;n expresa y por escrito de Armario M&oacute;vil.</p>
<p>El Sitio puede contener enlaces a otros sitios lo cual no indica que sean propiedad u operados por Armario M&oacute;vil S.A. En virtud que Armario M&oacute;vil no tiene control sobre tales sitios, NO ser&aacute; responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por da&ntilde;os o p&eacute;rdidas ocasionadas por la utilizaci&oacute;n de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relaci&oacute;n, aprobaci&oacute;n, respaldo de Armario M&oacute;vil S.A. a dichos sitios y sus contenidos.</p>
<p class="text-grey font-weight-bold"><strong>18 INDEMNIZACI&Oacute;N</strong></p>
<p>El Usuario indemnizar&aacute; y mantendr&aacute; indemne a Armario M&oacute;vil S.A., empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio o por su incumplimiento los T&eacute;rminos y Condiciones Generales y dem&aacute;s Pol&iacute;ticas que se entienden incorporadas al presente o por la violaci&oacute;n de cuales quiera leyes o derechos de terceros, incluyendo los honorarios de abogados en una cantidad razonable.</p>
<ol class="text-grey font-weight-bold" start="19">
<li><strong> DECLARACIONES</strong></li>
</ol>
<p><strong>19.1. DE LICITUD DE FONDOS</strong></p>
<p>EL USUARIO, siendo conocedor de las disposiciones legales para la Prevenci&oacute;n, Detecci&oacute;n y erradicaci&oacute;n del Delito de Lavado de Activos y del Financiamiento de Delitos declara que los recursos y fondos que emplea para la gesti&oacute;n comercial, son l&iacute;citos y consecuentemente no provienen de ninguna actividad relacionada con la producci&oacute;n, consumo, comercializaci&oacute;n de sustancias estupefacientes y psicotr&oacute;picas, o cualquier otra actividad tipificada en la ley de sustancias estupefacientes y psicotr&oacute;picas y otras leyes conexas, en tal virtud autoriza expresamente, libre y voluntaria a Armario M&oacute;vil S.A. a realizar el an&aacute;lisis para corroborar la licitud de fondos y bienes materia del presente contrato-</p>
<p><strong>19.2. ACTUALIZACI&Oacute;N</strong></p>
<p>EL USUARIO declara que la informaci&oacute;n contenida en este documento es verdadera, completa y proporcionada de modo confiable y actualizada, conocer que es obligaci&oacute;n de cada USUARIO, actualizar anualmente los datos personales, as&iacute; como el comunicar y documentar a Armario M&oacute;vil S.A. de manera inmediata cambio de informaci&oacute;n y proporcionar la documentaci&oacute;n e informaci&oacute;n que me fuera solicitada.</p>
<p>&nbsp;</p>

<div class="d-flex justify-content-center my-3">
    <button class="btn btn-primary font-weight-bold ml-2 px-5" type="button" data-dismiss="modal">Aceptar</button>
</div>

</span>


                </div>
        </div>
    </div>
</div>
